# Reading images using scikit-image

In [1]:
# importing the libraries
import numpy as np
from skimage import io, img_as_float, img_as_ubyte

In [2]:
# reading an image
img = io.imread('images/dog.jpg')
print(img) 

[[[ 56  60   9]
  [ 56  60   9]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 55  59   8]
  ...
  [139 146  76]
  [139 146  76]
  [139 146  76]]

 ...

 [[ 57  63  17]
  [ 57  63  17]
  [ 56  62  16]
  ...
  [231 201 175]
  [229 199 171]
  [228 198 170]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [228 201 174]
  [230 200 174]
  [230 200 174]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [227 200 173]
  [230 200 174]
  [231 201 175]]]


In [3]:
# shape of the images
print(img.shape) # (Y, X, C)

(480, 640, 3)


In [4]:
# converting into float -> better to convert one type to other type
img2 = img_as_float(img)
print(img2)

[[[0.21960784 0.23529412 0.03529412]
  [0.21960784 0.23529412 0.03529412]
  [0.21960784 0.23529412 0.03529412]
  ...
  [0.54901961 0.57647059 0.30196078]
  [0.54901961 0.57647059 0.30196078]
  [0.54901961 0.57647059 0.30196078]]

 [[0.21568627 0.23137255 0.03137255]
  [0.21568627 0.23137255 0.03137255]
  [0.21960784 0.23529412 0.03529412]
  ...
  [0.54901961 0.57647059 0.30196078]
  [0.54901961 0.57647059 0.30196078]
  [0.54901961 0.57647059 0.30196078]]

 [[0.21568627 0.23137255 0.03137255]
  [0.21568627 0.23137255 0.03137255]
  [0.21568627 0.23137255 0.03137255]
  ...
  [0.54509804 0.57254902 0.29803922]
  [0.54509804 0.57254902 0.29803922]
  [0.54509804 0.57254902 0.29803922]]

 ...

 [[0.22352941 0.24705882 0.06666667]
  [0.22352941 0.24705882 0.06666667]
  [0.21960784 0.24313725 0.0627451 ]
  ...
  [0.90588235 0.78823529 0.68627451]
  [0.89803922 0.78039216 0.67058824]
  [0.89411765 0.77647059 0.66666667]]

 [[0.22745098 0.25098039 0.0627451 ]
  [0.22352941 0.24705882 0.05882353]


In [5]:
# another method converting into float using astype()
img3 = img.astype(np.float)
print(img3)

[[[ 56.  60.   9.]
  [ 56.  60.   9.]
  [ 56.  60.   9.]
  ...
  [140. 147.  77.]
  [140. 147.  77.]
  [140. 147.  77.]]

 [[ 55.  59.   8.]
  [ 55.  59.   8.]
  [ 56.  60.   9.]
  ...
  [140. 147.  77.]
  [140. 147.  77.]
  [140. 147.  77.]]

 [[ 55.  59.   8.]
  [ 55.  59.   8.]
  [ 55.  59.   8.]
  ...
  [139. 146.  76.]
  [139. 146.  76.]
  [139. 146.  76.]]

 ...

 [[ 57.  63.  17.]
  [ 57.  63.  17.]
  [ 56.  62.  16.]
  ...
  [231. 201. 175.]
  [229. 199. 171.]
  [228. 198. 170.]]

 [[ 58.  64.  16.]
  [ 57.  63.  15.]
  [ 56.  62.  16.]
  ...
  [228. 201. 174.]
  [230. 200. 174.]
  [230. 200. 174.]]

 [[ 58.  64.  16.]
  [ 57.  63.  15.]
  [ 56.  62.  16.]
  ...
  [227. 200. 173.]
  [230. 200. 174.]
  [231. 201. 175.]]]


C:\Users\admin\AppData\Local\Temp\ipykernel_2752\4277330571.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  img3 = img.astype(np.float)


In [6]:
# converting back the float datatype to 8 bit integer data
img8bit = img_as_ubyte(img2)
print(img8bit)

[[[ 56  60   9]
  [ 56  60   9]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 55  59   8]
  ...
  [139 146  76]
  [139 146  76]
  [139 146  76]]

 ...

 [[ 57  63  17]
  [ 57  63  17]
  [ 56  62  16]
  ...
  [231 201 175]
  [229 199 171]
  [228 198 170]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [228 201 174]
  [230 200 174]
  [230 200 174]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [227 200 173]
  [230 200 174]
  [231 201 175]]]


# Reading images using OpenCV

In [7]:
import cv2

In [8]:
# opencv reads image as BGR instead of RGB

In [9]:
# reading an image
img_cv2 = cv2.imread('images/dog.jpg')
print(img_cv2)

[[[  9  60  56]
  [  9  60  56]
  [  9  60  56]
  ...
  [ 77 147 140]
  [ 77 147 140]
  [ 77 147 140]]

 [[  8  59  55]
  [  8  59  55]
  [  9  60  56]
  ...
  [ 77 147 140]
  [ 77 147 140]
  [ 77 147 140]]

 [[  8  59  55]
  [  8  59  55]
  [  8  59  55]
  ...
  [ 76 146 139]
  [ 76 146 139]
  [ 76 146 139]]

 ...

 [[ 17  63  57]
  [ 17  63  57]
  [ 16  62  56]
  ...
  [175 201 231]
  [171 199 229]
  [170 198 228]]

 [[ 16  64  58]
  [ 15  63  57]
  [ 16  62  56]
  ...
  [174 201 228]
  [174 200 230]
  [174 200 230]]

 [[ 16  64  58]
  [ 15  63  57]
  [ 16  62  56]
  ...
  [173 200 227]
  [174 200 230]
  [175 201 231]]]


In [10]:
# coverting the BGR image to gray image
gray_image = cv2.imread('images/dog.jpg', 0)
print(gray_image)

[[ 53  53  53 ... 137 137 137]
 [ 52  52  53 ... 137 137 137]
 [ 52  52  52 ... 136 136 136]
 ...
 [ 56  56  55 ... 207 205 204]
 [ 57  56  55 ... 206 206 206]
 [ 57  56  55 ... 205 206 207]]


In [11]:
# reading as a BGR image
color_image = cv2.imread('images/dog.jpg', 1)
print(color_image)

[[[  9  60  56]
  [  9  60  56]
  [  9  60  56]
  ...
  [ 77 147 140]
  [ 77 147 140]
  [ 77 147 140]]

 [[  8  59  55]
  [  8  59  55]
  [  9  60  56]
  ...
  [ 77 147 140]
  [ 77 147 140]
  [ 77 147 140]]

 [[  8  59  55]
  [  8  59  55]
  [  8  59  55]
  ...
  [ 76 146 139]
  [ 76 146 139]
  [ 76 146 139]]

 ...

 [[ 17  63  57]
  [ 17  63  57]
  [ 16  62  56]
  ...
  [175 201 231]
  [171 199 229]
  [170 198 228]]

 [[ 16  64  58]
  [ 15  63  57]
  [ 16  62  56]
  ...
  [174 201 228]
  [174 200 230]
  [174 200 230]]

 [[ 16  64  58]
  [ 15  63  57]
  [ 16  62  56]
  ...
  [173 200 227]
  [174 200 230]
  [175 201 231]]]


In [12]:
# converting the BGR channel to RGB channel
img_opencv = cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB)
print(img_opencv)

[[[ 56  60   9]
  [ 56  60   9]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 56  60   9]
  ...
  [140 147  77]
  [140 147  77]
  [140 147  77]]

 [[ 55  59   8]
  [ 55  59   8]
  [ 55  59   8]
  ...
  [139 146  76]
  [139 146  76]
  [139 146  76]]

 ...

 [[ 57  63  17]
  [ 57  63  17]
  [ 56  62  16]
  ...
  [231 201 175]
  [229 199 171]
  [228 198 170]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [228 201 174]
  [230 200 174]
  [230 200 174]]

 [[ 58  64  16]
  [ 57  63  15]
  [ 56  62  16]
  ...
  [227 200 173]
  [230 200 174]
  [231 201 175]]]
